name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install project dependencies
      - name: Install dependencies
        run: npm install && npm list

      # 4. Check Jest binary permissions
      - name: Check Jest binary
        run: ls -la ./node_modules/.bin/

      # 5. Ensure permissions for Jest and ESLint binaries
      - name: Fix binary permissions
        run: chmod +x ./node_modules/.bin/jest ./node_modules/.bin/eslint

      # 6. Lint the code using ESLint
      - name: Run ESLint
        run: npm run lint

      # 7. Run unit tests
      - name: Run tests
        run: npm test
