name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install project dependencies
      - name: Install dependencies
        run: npm install && npm list

      # 4. Check ESLint binary permissions
      - name: Check ESLint binary
        run: ls -la ./node_modules/.bin/

      # 5. Ensure permissions and run ESLint
      - name: Run ESLint
        run: chmod +x ./node_modules/.bin/eslint && npm run lint

      # 6. Run unit tests
      - name: Run tests
        run: npm test
